//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperProUL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public string User { get; set; }
        public int Purpose { get; set; }
        public string Status { get; set; }
    
        public virtual Purpose Purpose1 { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
